spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:postgresql://localhost:5432/blueprintsdb
spring.datasource.username=postgres
spring.datasource.password=blueprints123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eliminar puntos duplicados consecutivos
# spring.profiles.active=redundancy
# Conserva 1 de cada 2 puntos
spring.profiles.active=undersampling
# Si no se activa ninguno, se usa el filtro identidad (sin filtrado)
